import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { ThemeProvider } from "@/components/utils/theme-provider"
import NavBar from "@/components/main/nav-bar";
import Footer from "@/components/Footer";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning>
    <head  />
    <body className={fontSans.className }>
       <ThemeProvider
       attribute="class"
       defaultTheme="dark"
       themes={["light", "dark", "system"]}
       enableSystem
       disableTransitionOnChange
     >
     
      <NavBar />
   
      <main className="bg-grid-black/[0.04] antialiased dark:bg-grid-white/[0.04] flex min-h-screen flex-col items-center justify-between " >
       

       
        {children} 
      </main>
      <Footer/>
     </ThemeProvider></body> 
    </html>
  );
}
